#!/bin/bash

echo "================================================"
echo "GitHub Secrets Verification for chat-humanitarian-agent"
echo "================================================"
echo ""
echo "This script will help you verify that all required GitHub Secrets"
echo "are configured for building the Docker image."
echo ""
echo "REQUIRED GitHub Secrets (Repository > Settings > Secrets and variables > Actions):"
echo ""
echo "1. NUXT_UI_PRO_LICENSE"
echo "   Purpose: Nuxt UI Pro license key"
echo "   How to get: From your Nuxt UI Pro purchase"
echo ""
echo "2. NUXT_PUBLIC_SITE_URL"
echo "   Purpose: Production site URL"
echo "   Value: https://chat.baena.ai"
echo ""
echo "3. NUXT_PUBLIC_SUPABASE_URL"
echo "   Purpose: Supabase project URL"
echo "   How to get: Supabase Dashboard > Project > Settings > API"
echo ""
echo "4. NUXT_PUBLIC_SUPABASE_KEY"
echo "   Purpose: Supabase anon/public key"
echo "   How to get: Supabase Dashboard > Project > Settings > API > anon/public key"
echo ""
echo "5. NUXT_PUBLIC_FLOWISE_URL  ⚠️  CRITICAL"
echo "   Purpose: Flowise prediction endpoint"
echo "   Value: https://flowise.baena.site/api/v1/prediction/YOUR-CHATFLOW-ID"
echo ""
echo "6. NUXT_PUBLIC_FLOWISE_API_KEY  ⚠️  CRITICAL"
echo "   Purpose: Flowise API key for authentication"
echo "   How to get: Flowise Dashboard > API Keys"
echo ""
echo "================================================"
echo ""
echo "To verify secrets are set:"
echo "1. Go to: https://github.com/Jesus-Baena/chat-humanitarian-agent/settings/secrets/actions"
echo "2. Check that all 6 secrets listed above are present"
echo "3. If any are missing, click 'New repository secret' to add them"
echo ""
echo "================================================"
echo ""
echo "CURRENT BUILD STATUS:"
echo ""
echo "Last commit on main branch:"
git log -1 --oneline main
echo ""
echo "To trigger a new build with updated secrets:"
echo "  git commit --allow-empty -m 'chore: trigger rebuild with secrets'"
echo "  git push"
echo ""
echo "Then check: https://github.com/Jesus-Baena/chat-humanitarian-agent/actions"
echo "================================================"
