#!/bin/bash
# Complete Diagnostic Script for "No completion backend configured" Error

echo "🔍 Complete Flowise Configuration Diagnostic"
echo "=============================================="
echo ""

echo "📋 STEP 1: Check Local Environment"
echo "-----------------------------------"
if [ -f .env ]; then
  source .env
  echo "✅ .env file found"
  echo ""
  echo "Local values:"
  echo "  NUXT_PUBLIC_FLOWISE_URL: ${NUXT_PUBLIC_FLOWISE_URL:0:50}..."
  echo "  NUXT_PUBLIC_FLOWISE_API_KEY: ${NUXT_PUBLIC_FLOWISE_API_KEY:0:20}..."
else
  echo "❌ .env file not found"
fi
echo ""

echo "📋 STEP 2: GitHub Secrets Status"
echo "---------------------------------"
echo "⚠️  Cannot check GitHub Secrets directly from CLI without authentication"
echo ""
echo "👉 Please manually verify at:"
echo "   https://github.com/Jesus-Baena/chat-humanitarian-agent/settings/secrets/actions"
echo ""
echo "Required secrets (click each to verify it exists):"
echo "  - NUXT_UI_PRO_LICENSE"
echo "  - NUXT_PUBLIC_SITE_URL"
echo "  - NUXT_PUBLIC_SUPABASE_URL"
echo "  - NUXT_PUBLIC_SUPABASE_KEY (or NUXT_PUBLIC_SUPABASE_ANON_KEY)"
echo "  - NUXT_PUBLIC_FLOWISE_URL ⚠️  CRITICAL"
echo "  - NUXT_PUBLIC_FLOWISE_API_KEY ⚠️  CRITICAL"
echo ""

echo "📋 STEP 3: Check Latest GitHub Actions Build"
echo "---------------------------------------------"
echo "👉 Check the latest workflow run at:"
echo "   https://github.com/Jesus-Baena/chat-humanitarian-agent/actions"
echo ""
echo "In the 'Verify build arguments' step, you should see:"
echo "  NUXT_PUBLIC_FLOWISE_URL: ✅ Set"
echo "  NUXT_PUBLIC_FLOWISE_API_KEY: ✅ Set"
echo ""
echo "If you see ❌ Missing, the GitHub Secret is not set!"
echo ""

echo "📋 STEP 4: Check Production Runtime"
echo "------------------------------------"
echo "👉 Visit the test page in production:"
echo "   https://chat.baena.ai/test-flowise"
echo ""
echo "Expected output:"
echo "  Flowise URL: https://flowise.baena.site/api/v1/prediction/..."
echo "  Flowise API Key: ***SET*** (length: 47)"
echo ""
echo "If you see 'NOT SET', the values were NOT baked into the Docker image!"
echo ""

echo "📋 STEP 5: Check Deployed Container (SSH Required)"
echo "---------------------------------------------------"
echo "If you have SSH access to your server, run:"
echo ""
echo "  # Check container environment"
echo "  docker ps | grep chat"
echo "  docker exec <container-id> env | grep FLOWISE"
echo ""
echo "  # This will show RUNTIME env vars (from docker-compose)"
echo "  # But these DON'T affect client-side code!"
echo ""

echo "📋 DIAGNOSIS SUMMARY"
echo "--------------------"
echo ""
echo "The error 'No completion backend configured' means:"
echo "  ❌ flowiseUrl is undefined in the client-side JavaScript"
echo ""
echo "This happens because:"
echo "  1. GitHub Secrets NUXT_PUBLIC_FLOWISE_URL is NOT SET in the repository"
echo "  2. OR: The Docker image was built BEFORE the secret was added"
echo "  3. OR: The latest image hasn't been deployed yet"
echo ""
echo "✅ TO FIX:"
echo "----------"
echo ""
echo "1. Add GitHub Secrets (if not already done):"
echo "   https://github.com/Jesus-Baena/chat-humanitarian-agent/settings/secrets/actions"
echo ""
echo "   Add secret: NUXT_PUBLIC_FLOWISE_URL"
echo "   Value: $NUXT_PUBLIC_FLOWISE_URL"
echo ""
echo "   Add secret: NUXT_PUBLIC_FLOWISE_API_KEY"  
echo "   Value: $NUXT_PUBLIC_FLOWISE_API_KEY"
echo ""
echo "2. Trigger a NEW build (required!):"
echo "   https://github.com/Jesus-Baena/chat-humanitarian-agent/actions"
echo "   Click 'Build and Push Docker Image' → 'Run workflow'"
echo ""
echo "3. Wait for build to complete (~5 min)"
echo ""
echo "4. Verify in workflow logs:"
echo "   NUXT_PUBLIC_FLOWISE_URL: ✅ Set"
echo ""
echo "5. Deploy the new image:"
echo "   ./deploy-stack.sh"
echo ""
echo "6. Test:"
echo "   https://chat.baena.ai/test-flowise"
echo ""
echo "🔑 KEY INSIGHT:"
echo "---------------"
echo "Docker Swarm runtime environment variables (in docker-compose.prod.yml)"
echo "do NOT affect client-side code. Client values must be baked in at build time!"
echo ""
echo "The GitHub Actions workflow (.github/workflows/deploy.yml) passes secrets"
echo "as build arguments, which get embedded into the compiled JavaScript bundle."
echo ""
echo "Without GitHub Secrets set, the build args are empty, and the client code"
echo "is compiled with flowiseUrl = undefined!"
echo ""
