name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NUXT_UI_PRO_LICENSE=${{ secrets.NUXT_UI_PRO_LICENSE }}

      - name: Deployment Info
        run: |
          echo "✅ Docker image built and pushed to GitHub Container Registry"
          echo ""
          echo "📦 Image tags:"
          echo "${{ steps.meta.outputs.tags }}"
          echo ""
          echo "🚀 To deploy:"
          echo "  1. Image: ghcr.io/${{ github.repository }}:latest"
          echo "  2. Update: https://github.com/Jesus-Baena/swarm-infra/blob/main/web/docker-compose.yml"
          echo "  3. Or use Portainer UI to redeploy the 'web' stack"
          echo ""
          echo "📖 See DEPLOYMENT_WORKFLOW.md for details"
